// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAb7G09Z-h76b6-87rHJK92GK5LgYIH-Vk',
    appId: '1:1085630707865:web:e537e86da36300e2606008',
    messagingSenderId: '1085630707865',
    projectId: 'api-prognosticare',
    authDomain: 'api-prognosticare.firebaseapp.com',
    storageBucket: 'api-prognosticare.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhwYqPkFja56HZNrqmSyYY51K3euMrz0w',
    appId: '1:1085630707865:android:478228598db61a05606008',
    messagingSenderId: '1085630707865',
    projectId: 'api-prognosticare',
    storageBucket: 'api-prognosticare.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgQhTQb6lw4-_xpbp9lFS2Z2kFVsEnqCw',
    appId: '1:1085630707865:ios:71b2cc1b2c0c6ba5606008',
    messagingSenderId: '1085630707865',
    projectId: 'api-prognosticare',
    storageBucket: 'api-prognosticare.appspot.com',
    iosClientId: '1085630707865-c8l1aj4vvo4k6t0ihgq257q4alfqcbib.apps.googleusercontent.com',
    iosBundleId: 'com.example.prognosticare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgQhTQb6lw4-_xpbp9lFS2Z2kFVsEnqCw',
    appId: '1:1085630707865:ios:036d6cbb0c89e31f606008',
    messagingSenderId: '1085630707865',
    projectId: 'api-prognosticare',
    storageBucket: 'api-prognosticare.appspot.com',
    iosClientId: '1085630707865-e2vv7qsi2nnkdgah7hijvu6jhf84pjtj.apps.googleusercontent.com',
    iosBundleId: 'com.example.prognosticare.RunnerTests',
  );
}
